language: perl

perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env:
  - "HARNESS_OPTIONS=j9"

install:
  - "cpanm -qn Perl::Critic && cpanm -qn --installdeps ."

jobs:
  include:
    - stage: linting
      script: perlcritic lib t
    - stage: testing
      script: prove -Ilib -r t
    - stage: checking
      script: find lib t -type f -exec perl -Ilib -c {} \;

notifications:
  email: false