language: perl

perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env:
  - "HARNESS_OPTIONS=j9"

install:
  - "cpanm -M https://cpan.metacpan.org -n --installdeps ."

notifications:
  email: false
