language: perl

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

  # Temporarily Disable Perls < 5.22
  # Error downloading archive: https://storage.googleapis.com/travis-ci-language-archives/perl/binaries/ubuntu/16.04/x86_64/perl-5.20.tar.bz2
  # - "5.20"
  # - "5.18"
  # - "5.16"
  # - "5.14"

env:
  - "HARNESS_OPTIONS=j9"

install:
  - "cpanm -qn Perl::Critic && cpanm -qn --installdeps ."

jobs:
  include:
    - stage: critique
      script: perlcritic lib t

notifications:
  email: false