#!/bin/bash

# Ensure release version is explicit
if [ ! -n "$1" ]; then
  echo 'No release version!' && exit 0;
fi

# Check the repo is in ready-state
if ! git diff-index --quiet HEAD --; then
  echo "Uncommitted changes!" && exit 0;
fi

# Test fake build before release
if ! dzil test; then
  echo "Build test failed!" && exit 0;
fi

# Cleanup the mess
dzil clean

# Delete existing POD documents
find lib -type f -name \*.pod -exec rm {} \;

# Regenerate all necessary POD documents
perl -Ilib bin/pod

# Push generated POD changes
if ! git diff-index --quiet HEAD --; then
  git add . && git commit -m 'Updated documentation'
fi

# Build, Tag, and Push Package Release
V=$1 dzil release
