
=encoding utf8

=head1 NAME

Data::Object::Func::Number::To

=cut

=head1 ABSTRACT

Data-Object Number Function (To) Class

=cut

=head1 SYNOPSIS

  use Data::Object::Func::Number::To;

  my $func = Data::Object::Func::Number::To->new(@args);

  $func->execute;

=cut

=head1 DESCRIPTION

Data::Object::Func::Number::To is a function object for Data::Object::Number.

=cut

=head1 METHODS

This package implements the following methods.

=cut

=head2 execute

  execute() : Object

Executes the function logic and returns the result.

=over 4

=item execute example

  my $data = Data::Object::Number->new(5);

  my $func = Data::Object::Func::Number::To->new(
    arg1 => $data,
    arg2 => 8
  );

  my $result = $func->execute;

=back

=cut

=head2 mapping

  mapping() : (Str)

Returns the ordered list of named function object arguments.

=over 4

=item mapping example

  my @data = $self->mapping;

=back

=cut
