
=encoding utf8

=head1 NAME

Data::Object::Func::Number::Upto

=cut

=head1 ABSTRACT

Data-Object Number Function (Upto) Class

=cut

=head1 SYNOPSIS

  use Data::Object::Func::Number::Upto;

  my $func = Data::Object::Func::Number::Upto->new(@args);

  $func->execute;

=cut

=head1 DESCRIPTION

Data::Object::Func::Number::Upto is a function object for Data::Object::Number.

=cut

=head1 METHODS

This package implements the following methods.

=cut

=head2 execute

  my $data = Data::Object::Number->new(23);

  my $func = Data::Object::Func::Number::Upto->new(
    arg1 => $data,
    arg2 => 14
  );

  my $result = $func->execute;

Executes the function logic and returns the result.

=cut

=head2 mapping

  my @data = $self->mapping;

Returns the ordered list of named function object arguments.

=cut
