
=encoding utf8

=head1 NAME

Data::Object::Func::Hash::Tail

=cut

=head1 ABSTRACT

Data-Object Hash Function (Tail) Class

=cut

=head1 SYNOPSIS

  use Data::Object::Func::Hash::Tail;

  my $func = Data::Object::Func::Hash::Tail->new(@args);

  $func->execute;

=cut

=head1 DESCRIPTION

Data::Object::Func::Hash::Tail is a function object for Data::Object::Hash.

=cut

=head1 METHODS

This package implements the following methods.

=cut

=head2 execute

  my $data = Data::Object::Hash->new({1..4});

  my $func = Data::Object::Func::Hash::Tail->new(
    arg1 => $data
  );

  my $result = $func->execute;

Executes the function logic and returns the result.

=cut

=head2 mapping

  my @data = $self->mapping;

Returns the ordered list of named function object arguments.

=cut
