
=encoding utf8

=head1 NAME

Data::Object::Func::Any::Ne

=cut

=head1 ABSTRACT

Data-Object Any Function (Ne) Class

=cut

=head1 SYNOPSIS

  use Data::Object::Func::Any::Ne;

  my $func = Data::Object::Func::Any::Ne->new(@args);

  $func->execute;

=cut

=head1 DESCRIPTION

Data::Object::Func::Any::Ne is a function object for Data::Object::Any.

=cut

=head1 METHODS

This package implements the following methods.

=cut

=head2 execute

  my $data = Data::Object::Any->new(sub {1});

  my $func = Data::Object::Func::Any::Ne->new(
    arg1 => $data,
    arg2 => ''
  );

  my $result = $func->execute;

Executes the function logic and returns the result.

=cut

=head2 mapping

  my @data = $self->mapping;

Returns the ordered list of named function object arguments.

=cut
