
=encoding utf8

=head1 NAME

do

=cut

=head1 ABSTRACT

Minimalist Perl Development Framework

=cut

=head1 SYNOPSIS

  #!perl

  use do;

  my $phrase = do('cast', 'hello world');

  $phrase->titlecase->say;

=cut

=head1 DESCRIPTION

The "do" package is focused on simplicity and productivity. It encapsulates the
L<Data::Object> framework features, is minimalist, and is designed for
scripting.

=cut
