
=encoding utf8

=head1 NAME

Data::Object::Exception

=cut

=head1 ABSTRACT

Data-Object Exception Class

=cut

=head1 SYNOPSIS

  use Data::Object::Exception;

  my $exception = Data::Object::Exception->new;

  $exception->throw('Something went wrong');

=cut

=head1 DESCRIPTION

Data::Object::Exception provides functionality for creating, throwing,
catching, and introspecting exception objects.

=cut

=head1 METHODS

This package implements the following methods.

=cut

=head2 data

  my $data = $exception->data();

data

=cut

=head2 dump

  my $dump = $exception->dump();

The dump method returns a string representation of the underlying data.

=cut

=head2 explain

  my $explain = $exception->explain();

Returns a complete stack trace if the exception was thrown.

=cut

=head2 throw

  $exception->throw();

Throw error with object and message.

=cut
